import { AGENTS, getAllTasks } from '@/lib/agents/mock';

export const ORG_PROFILE = {
  name: 'House of Omnia',
  market: 'Ladies-only luxury commerce',
  customerRule: 'All demo customers are women because the company sells only to ladies.',
  staffingRule: 'The operating team is mostly male, with Omnia AI coordinating work across rooms.',
  currency: 'AED',
  date: '2026-05-25',
};

export type Tone = 'good' | 'warn' | 'bad' | 'info' | 'gold';

export type ExecutiveMetric = {
  label: string;
  value: string;
  delta: string;
  detail: string;
  tone: Tone;
};

export type IntelligenceDecision = {
  id: string;
  title: string;
  owner: string;
  status: 'approve' | 'monitor' | 'assign' | 'blocked';
  confidence: number;
  impact: string;
  evidence: string[];
  nextStep: string;
};

export type CustomerSegment = {
  name: string;
  count: number;
  revenue: string;
  conversion: string;
  signal: string;
  action: string;
  tone: Tone;
};

export const EXECUTIVE_METRICS: ExecutiveMetric[] = [
  {
    label: 'Revenue today',
    value: 'AED 87,420',
    delta: '+12.4%',
    detail: '78% from WhatsApp-assisted orders',
    tone: 'good',
  },
  {
    label: 'Open opportunity',
    value: 'AED 64,850',
    delta: '+AED 9.8k',
    detail: 'Ghost carts and cross-sell pipeline',
    tone: 'gold',
  },
  {
    label: 'Risk exposure',
    value: 'AED 18,740',
    delta: '4 decisions',
    detail: 'Finance, inventory, and pricing blockers',
    tone: 'warn',
  },
  {
    label: 'Women customers',
    value: '1,284',
    delta: '+37 this week',
    detail: 'Ladies-only customer base',
    tone: 'info',
  },
];

export const STAFF_ROSTER = AGENTS.filter((agent) => agent.kind === 'member').map((agent) => ({
  id: agent.id,
  name: agent.short_name,
  role: agent.for_user_role || (agent.id === 'agent_mahmoud' ? 'owner' : 'operator'),
  gender: 'male',
  online: agent.online,
  status: agent.status || 'available',
  score: Math.round(agent.performance_score * 100),
  skills: agent.skills.slice(0, 4),
  workload: getAllTasks().filter((task) => task.assignee_agent_id === agent.id && task.status !== 'completed').length,
}));

export const CUSTOMER_SEGMENTS: CustomerSegment[] = [
  {
    name: 'Bridal collectors',
    count: 146,
    revenue: 'AED 318k',
    conversion: '18.4%',
    signal: 'Wedding deadline messages and bridal set saves',
    action: 'Route every bridal chat to senior WhatsApp closers within 4 minutes.',
    tone: 'gold',
  },
  {
    name: 'Gifting daughters',
    count: 232,
    revenue: 'AED 204k',
    conversion: '11.7%',
    signal: 'Mother-daughter gift phrases and Eid reminders',
    action: 'Offer gift wrap, Arabic card copy, and delivery certainty.',
    tone: 'good',
  },
  {
    name: 'VIP repeat buyers',
    count: 84,
    revenue: 'AED 441k',
    conversion: '24.9%',
    signal: 'High LTV women returning from WhatsApp and direct',
    action: 'Show private drops before public catalogue release.',
    tone: 'info',
  },
  {
    name: 'Price-sensitive visitors',
    count: 311,
    revenue: 'AED 96k',
    conversion: '5.2%',
    signal: 'Cart exits after shipping, COD, or BNPL questions',
    action: 'Use concierge reassurance before discounting luxury products.',
    tone: 'warn',
  },
];

export const OMNIA_DECISIONS: IntelligenceDecision[] = [
  {
    id: 'd1',
    title: 'Escalate Mariam K. bridal deadline before Abdallah returns',
    owner: 'Mahmoud',
    status: 'approve',
    confidence: 92,
    impact: 'AED 4,200 protected revenue',
    evidence: ['KSA bridal deadline is Thursday', 'Assigned agent is offline', 'Customer has high urgency language'],
    nextStep: 'Move the thread to Abdelrahman and notify finance to pre-clear payment.',
  },
  {
    id: 'd2',
    title: 'Correct Ruby Bangle price drift across .ae and .com',
    owner: 'Ez',
    status: 'assign',
    confidence: 88,
    impact: 'AED 14,600 monthly margin variance',
    evidence: ['13.6% store mismatch', 'Four WhatsApp objections mention price', 'No documented KSA exception'],
    nextStep: 'Confirm intended price, update both storefronts, and pin the decision.',
  },
  {
    id: 'd3',
    title: 'Keep BNPL as assisted-only for luxury bridal orders',
    owner: 'Mahmoud',
    status: 'monitor',
    confidence: 74,
    impact: 'Protects brand perception and cash collection',
    evidence: ['Tabby clears faster than Tamara', 'VIP buyers prefer bank transfer', 'Discount language hurts bridal positioning'],
    nextStep: 'Let finance offer BNPL only after a WhatsApp manager approves the case.',
  },
  {
    id: 'd4',
    title: 'Increase Moonstone Pendant stock before weekend demand',
    owner: 'Ez',
    status: 'blocked',
    confidence: 81,
    impact: 'AED 18,000 forecasted sell-through',
    evidence: ['Only 3 left on .ae', '24 sold in 7 days', 'Search demand rising for moonstone gift'],
    nextStep: 'Approve supplier reorder and update pre-order promise by 18:00.',
  },
];

export const MANAGEMENT_QUEUE = [
  {
    lane: 'Commercial',
    owner: 'Mahmoud',
    items: [
      'Approve KSA bridal exception pricing',
      'Review high-value COD rules for ladies-only customer base',
      'Decide Eid limited edition drop quantity',
    ],
  },
  {
    lane: 'Operations',
    owner: 'Ez',
    items: [
      'Sync Shopify and WooCommerce inventory',
      'Close Ruby Bangle price drift',
      'Confirm Moonstone supplier delivery promise',
    ],
  },
  {
    lane: 'Customer Desk',
    owner: 'Abdelrahman',
    items: [
      'Recover four abandoned bridal carts',
      'Reassign stalled KSA WhatsApp thread',
      'Audit Arabic response quality for female VIP customers',
    ],
  },
  {
    lane: 'Marketing',
    owner: 'Ahmed',
    items: [
      'Refresh meta copy for ladies bridal intent',
      'Build Eid WhatsApp broadcast segments',
      'Mine customer phrases into Google keyword list',
    ],
  },
];

export const INTEGRATIONS = [
  { name: 'WhatsApp Business', status: 'online', owner: 'Abdelrahman', latency: '1.8s', risk: 'low' },
  { name: 'Shopify .ae', status: 'online', owner: 'Ez', latency: '2.3s', risk: 'medium' },
  { name: 'WooCommerce .com', status: 'drift', owner: 'Ez', latency: '4.1s', risk: 'high' },
  { name: 'Google Search Console', status: 'online', owner: 'Ahmed', latency: '2.7s', risk: 'low' },
  { name: 'Finance verification', status: 'queue', owner: 'Mahmoud', latency: '9m', risk: 'medium' },
];

export const ACCESS_REQUESTS = [
  { name: 'Arslan', role: 'WhatsApp refund approvals', reason: 'Can clear low-risk payment screenshots faster', risk: 'medium' },
  { name: 'Ahmed', role: 'Google keyword publishing', reason: 'Needs direct publish for campaign pages', risk: 'low' },
  { name: 'Mohamed', role: 'Read-only customer profiles', reason: 'Onboarding on ladies-only concierge standards', risk: 'low' },
];

const customers = [
  {
    id: 'cus_noura',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Noura',
    last_name: 'Al Mansoori',
    email: 'noura@example.com',
    phone: '+971501112233',
    city: 'Dubai',
    country: 'UAE',
    total_orders: 9,
    total_spent: 18400,
    created_at: '2026-01-14T09:30:00Z',
  },
  {
    id: 'cus_aisha',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Aisha',
    last_name: 'Al Suwaidi',
    email: 'aisha@example.com',
    phone: '+971522224455',
    city: 'Abu Dhabi',
    country: 'UAE',
    total_orders: 6,
    total_spent: 9200,
    created_at: '2026-02-05T12:20:00Z',
  },
  {
    id: 'cus_mariam',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Mariam',
    last_name: 'Al Harbi',
    email: 'mariam@example.com',
    phone: '+966555441122',
    city: 'Riyadh',
    country: 'KSA',
    total_orders: 4,
    total_spent: 7600,
    created_at: '2026-03-18T16:05:00Z',
  },
  {
    id: 'cus_latifa',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Latifa',
    last_name: 'Al Qasimi',
    email: 'latifa@example.com',
    phone: '+971507778899',
    city: 'Sharjah',
    country: 'UAE',
    total_orders: 12,
    total_spent: 26800,
    created_at: '2025-11-02T11:00:00Z',
  },
  {
    id: 'cus_reem',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Reem',
    last_name: 'Al Nuaimi',
    email: 'reem@example.com',
    phone: '+971565557788',
    city: 'Dubai',
    country: 'UAE',
    total_orders: 3,
    total_spent: 4100,
    created_at: '2026-04-09T14:45:00Z',
  },
  {
    id: 'cus_hessa',
    org_id: '00000000-0000-0000-0000-000000000001',
    first_name: 'Hessa',
    last_name: 'Al Falasi',
    email: 'hessa@example.com',
    phone: '+971544445566',
    city: 'Dubai',
    country: 'UAE',
    total_orders: 2,
    total_spent: 2350,
    created_at: '2026-05-03T17:15:00Z',
  },
];

const products = [
  {
    id: 'prod_ruby_bangle',
    org_id: '00000000-0000-0000-0000-000000000001',
    store_id: 'store_shopify',
    external_id: 'sh_1001',
    sku: 'OMN-RB-001',
    title: 'Ruby Bangle for Ladies',
    category: 'Bracelets',
    price: 950,
    compare_at_price: 1100,
    stock_quantity: 18,
    stock_status: 'in_stock',
    is_on_sale: false,
    vendor: 'Omnia Atelier',
    tags: ['ladies', 'ruby', 'bridal'],
    store_connections: { name: 'Omnia .ae', platform: 'shopify' },
  },
  {
    id: 'prod_moonstone',
    org_id: '00000000-0000-0000-0000-000000000001',
    store_id: 'store_shopify',
    external_id: 'sh_1002',
    sku: 'OMN-MP-002',
    title: 'Moonstone Pendant for Ladies',
    category: 'Pendants',
    price: 750,
    compare_at_price: null,
    stock_quantity: 3,
    stock_status: 'low_stock',
    is_on_sale: false,
    vendor: 'Omnia Atelier',
    tags: ['ladies', 'moonstone', 'gift'],
    store_connections: { name: 'Omnia .ae', platform: 'shopify' },
  },
  {
    id: 'prod_celestial',
    org_id: '00000000-0000-0000-0000-000000000001',
    store_id: 'store_woo',
    external_id: 'woo_4421',
    sku: 'OMN-LC-003',
    title: 'LE Celestial Bridal Set',
    category: 'Bridal Sets',
    price: 2400,
    compare_at_price: null,
    stock_quantity: 8,
    stock_status: 'in_stock',
    is_on_sale: false,
    vendor: 'Omnia Atelier',
    tags: ['ladies', 'limited edition', 'bridal'],
    store_connections: { name: 'Omnia .com', platform: 'woocommerce' },
  },
  {
    id: 'prod_oud_royal',
    org_id: '00000000-0000-0000-0000-000000000001',
    store_id: 'store_shopify',
    external_id: 'sh_1004',
    sku: 'OMN-PF-001',
    title: 'Oud Royal Perfume for Ladies',
    category: 'Perfume',
    price: 450,
    compare_at_price: null,
    stock_quantity: 42,
    stock_status: 'in_stock',
    is_on_sale: false,
    vendor: 'Omnia Fragrance',
    tags: ['ladies', 'oud', 'gift'],
    store_connections: { name: 'Omnia .ae', platform: 'shopify' },
  },
];

const conversations = [
  {
    id: 'conv_noura',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_noura',
    channel: 'whatsapp',
    channel_id: '+971501112233',
    status: 'open',
    last_message_preview: 'I sent the bank transfer screenshot. Can you confirm before delivery?',
    last_message_at: '2026-05-25T13:48:00Z',
    unread_count: 2,
    customer: customers[0],
  },
  {
    id: 'conv_mariam',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_mariam',
    channel: 'whatsapp',
    channel_id: '+966555441122',
    status: 'pending',
    last_message_preview: 'The bridal set must arrive before Thursday evening.',
    last_message_at: '2026-05-25T12:25:00Z',
    unread_count: 4,
    customer: customers[2],
  },
  {
    id: 'conv_latifa',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_latifa',
    channel: 'whatsapp',
    channel_id: '+971507778899',
    status: 'resolved',
    last_message_preview: 'Please reserve the private Eid drop for me.',
    last_message_at: '2026-05-24T19:10:00Z',
    unread_count: 0,
    customer: customers[3],
  },
];

const ghostCarts = [
  {
    id: 'gc_noura_1',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_noura',
    customer: customers[0],
    status: 'abandoned',
    items: [{ sku: 'OMN-RB-001', title: 'Ruby Bangle for Ladies', price: 950, quantity: 1 }],
    subtotal: 950,
    source: 'whatsapp',
    abandonment_reason: 'payment_confirmation',
    device_type: 'mobile',
    city: 'Dubai',
    country: 'UAE',
    created_at: '2026-05-25T12:52:00Z',
  },
  {
    id: 'gc_aisha_1',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_aisha',
    customer: customers[1],
    status: 'abandoned',
    items: [{ sku: 'OMN-MP-002', title: 'Moonstone Pendant for Ladies', price: 750, quantity: 2 }],
    subtotal: 1500,
    source: 'website',
    abandonment_reason: 'delivery_timing',
    device_type: 'mobile',
    city: 'Abu Dhabi',
    country: 'UAE',
    created_at: '2026-05-25T11:34:00Z',
  },
  {
    id: 'gc_latifa_1',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_latifa',
    customer: customers[3],
    status: 'recovered',
    items: [{ sku: 'OMN-LC-003', title: 'LE Celestial Bridal Set', price: 2400, quantity: 1 }],
    subtotal: 2400,
    source: 'whatsapp',
    abandonment_reason: 'vip_review',
    device_type: 'desktop',
    city: 'Sharjah',
    country: 'UAE',
    created_at: '2026-05-25T09:20:00Z',
  },
];

const orders = [
  {
    id: 'ord_1280',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_aisha',
    order_number: 'OMN-1280',
    status: 'pending',
    payment_status: 'pending',
    total: 1300,
    subtotal: 1300,
    item_count: 2,
    notes: 'Ladies gift order, requested evening delivery.',
    created_at: '2026-05-25T12:04:00Z',
    customer: customers[1],
  },
  {
    id: 'ord_1279',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_noura',
    order_number: 'OMN-1279',
    status: 'confirmed',
    payment_status: 'paid',
    total: 2150,
    subtotal: 2150,
    item_count: 3,
    notes: 'Bank transfer screenshot verified.',
    created_at: '2026-05-25T10:42:00Z',
    customer: customers[0],
  },
  {
    id: 'ord_1278',
    org_id: '00000000-0000-0000-0000-000000000001',
    customer_id: 'cus_mariam',
    order_number: 'OMN-1278',
    status: 'processing',
    payment_status: 'pending',
    total: 4200,
    subtotal: 4200,
    item_count: 1,
    notes: 'KSA bridal deadline Thursday.',
    created_at: '2026-05-24T18:30:00Z',
    customer: customers[2],
  },
];

export const MOCK_TABLES: Record<string, any[]> = {
  customers,
  customer_fingerprints: [
    {
      id: 'fp_noura_mobile',
      customer_id: 'cus_noura',
      fingerprint_hash: 'fp_noura_ios_14',
      confidence_score: 0.96,
      device_signals: { device_type: 'mobile', os: 'iOS 18', browser: 'Safari', screen: '390x844' },
      network_signals: { isp: 'du', connection: '5G' },
      behavior_signals: { avg_session: 520, scroll_depth: 0.84, click_rate: 0.31 },
      total_sessions: 24,
      total_orders: 9,
      total_spent: 18400,
      first_seen_at: '2026-01-14T09:30:00Z',
      last_seen_at: '2026-05-25T13:48:00Z',
    },
    {
      id: 'fp_aisha_mobile',
      customer_id: 'cus_aisha',
      fingerprint_hash: 'fp_aisha_android',
      confidence_score: 0.91,
      device_signals: { device_type: 'mobile', os: 'Android 15', browser: 'Chrome', screen: '412x915' },
      network_signals: { isp: 'Etisalat', connection: '5G' },
      behavior_signals: { avg_session: 410, scroll_depth: 0.71, click_rate: 0.22 },
      total_sessions: 18,
      total_orders: 6,
      total_spent: 9200,
      first_seen_at: '2026-02-05T12:20:00Z',
      last_seen_at: '2026-05-25T11:34:00Z',
    },
  ],
  customer_sessions: [
    {
      id: 'sess_noura_1',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_noura',
      source: 'whatsapp',
      landing_page: '/products/ruby-bangle',
      referrer: 'WhatsApp',
      device_type: 'mobile',
      browser: 'Safari',
      os: 'iOS',
      city: 'Dubai',
      country: 'UAE',
      pages_viewed: ['/products/ruby-bangle', '/checkout'],
      products_viewed: [{ sku: 'OMN-RB-001', title: 'Ruby Bangle for Ladies' }],
      time_on_site: 520,
      is_returning: true,
      created_at: '2026-05-25T12:50:00Z',
    },
    {
      id: 'sess_aisha_1',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_aisha',
      source: 'website',
      landing_page: '/collections/ladies-gifts',
      referrer: 'Google',
      device_type: 'mobile',
      browser: 'Chrome',
      os: 'Android',
      city: 'Abu Dhabi',
      country: 'UAE',
      pages_viewed: ['/collections/ladies-gifts', '/products/moonstone-pendant', '/checkout'],
      products_viewed: [{ sku: 'OMN-MP-002', title: 'Moonstone Pendant for Ladies' }],
      time_on_site: 388,
      is_returning: true,
      created_at: '2026-05-25T11:30:00Z',
    },
    {
      id: 'sess_reem_1',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_reem',
      source: 'app',
      landing_page: '/private-drop',
      referrer: 'Direct',
      device_type: 'desktop',
      browser: 'Chrome',
      os: 'macOS',
      city: 'Dubai',
      country: 'UAE',
      pages_viewed: ['/private-drop', '/products/celestial-bridal-set'],
      products_viewed: [{ sku: 'OMN-LC-003', title: 'LE Celestial Bridal Set' }],
      time_on_site: 760,
      is_returning: true,
      created_at: '2026-05-25T09:15:00Z',
    },
  ],
  ghost_carts: ghostCarts,
  conversations,
  messages: [
    {
      id: 'msg_noura_1',
      conversation_id: 'conv_noura',
      sender_type: 'customer',
      content: 'I sent the bank transfer screenshot. Can you confirm before delivery?',
      content_type: 'text',
      status: 'delivered',
      created_at: '2026-05-25T13:48:00Z',
    },
    {
      id: 'msg_mariam_1',
      conversation_id: 'conv_mariam',
      sender_type: 'customer',
      content: 'The bridal set must arrive before Thursday evening.',
      content_type: 'text',
      status: 'delivered',
      created_at: '2026-05-25T12:25:00Z',
    },
  ],
  conversation_order_intents: [
    {
      id: 'intent_mariam',
      org_id: '00000000-0000-0000-0000-000000000001',
      conversation_id: 'conv_mariam',
      customer_id: 'cus_mariam',
      confidence: 0.89,
      status: 'pending',
      extracted_items: [{ sku: 'OMN-LC-003', title: 'LE Celestial Bridal Set', price: 2400, quantity: 1 }],
      extracted_total: 2400,
      ai_summary: 'Female bridal customer needs guaranteed Riyadh delivery before Thursday.',
      created_at: '2026-05-25T12:30:00Z',
    },
  ],
  cross_sell_opportunities: [
    {
      id: 'xo_noura',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_noura',
      customer: customers[0],
      recommendation_type: 'bundle',
      reason: 'Noura bought bridal pieces and viewed matching ladies perfume twice.',
      confidence: 0.84,
      potential_value: 450,
      status: 'pending',
      created_at: '2026-05-25T13:00:00Z',
    },
    {
      id: 'xo_aisha',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_aisha',
      customer: customers[1],
      recommendation_type: 'recovery',
      reason: 'Aisha abandoned two Moonstone Pendants after delivery timing questions.',
      confidence: 0.78,
      potential_value: 1500,
      status: 'pending',
      created_at: '2026-05-25T11:40:00Z',
    },
    {
      id: 'xo_latifa',
      org_id: '00000000-0000-0000-0000-000000000001',
      customer_id: 'cus_latifa',
      customer: customers[3],
      recommendation_type: 'upsell',
      reason: 'Latifa is VIP and requested private Eid drop reservation.',
      confidence: 0.91,
      potential_value: 3200,
      status: 'pending',
      created_at: '2026-05-24T19:20:00Z',
    },
  ],
  orders,
  finance_verifications: [
    {
      id: 'fin_1279',
      org_id: '00000000-0000-0000-0000-000000000001',
      order_id: 'ord_1279',
      conversation_id: 'conv_noura',
      verification_type: 'payment',
      status: 'pending',
      priority: 'normal',
      risk_score: 0.22,
      risk_factors: ['bank transfer screenshot'],
      amount: 2150,
      currency: 'AED',
      payment_method: 'bank_transfer',
      notes: 'Verify bank transfer before release.',
      review_notes: null,
      reviewed_by: null,
      reviewed_at: null,
      created_at: '2026-05-25T13:50:00Z',
      order: orders[1],
    },
    {
      id: 'fin_1278',
      org_id: '00000000-0000-0000-0000-000000000001',
      order_id: 'ord_1278',
      conversation_id: 'conv_mariam',
      verification_type: 'manual',
      status: 'pending',
      priority: 'high',
      risk_score: 0.68,
      risk_factors: ['cross-border KSA delivery', 'bridal deadline', 'high value'],
      amount: 4200,
      currency: 'AED',
      payment_method: 'bank_transfer',
      notes: 'Need manual review because delivery deadline is tight.',
      review_notes: null,
      reviewed_by: null,
      reviewed_at: null,
      created_at: '2026-05-25T12:40:00Z',
      order: orders[2],
    },
  ],
  store_connections: [
    { id: 'store_shopify', org_id: '00000000-0000-0000-0000-000000000001', name: 'Omnia .ae', platform: 'shopify', is_active: true, last_sync_at: '2026-05-25T13:12:00Z' },
    { id: 'store_woo', org_id: '00000000-0000-0000-0000-000000000001', name: 'Omnia .com', platform: 'woocommerce', is_active: true, last_sync_at: '2026-05-25T10:02:00Z' },
  ],
  product_catalog: products,
  parity_drifts: [
    {
      id: 'drift_ruby',
      org_id: '00000000-0000-0000-0000-000000000001',
      product_a_id: 'prod_ruby_bangle',
      product_b_id: 'prod_ruby_bangle',
      drift_type: 'price',
      field_name: 'price',
      value_a: 'AED 950',
      value_b: 'AED 1100',
      severity: 'high',
      is_resolved: false,
      detected_at: '2026-05-25T09:12:00Z',
    },
  ],
  keywords: [
    {
      id: 'kw_bridal',
      org_id: '00000000-0000-0000-0000-000000000001',
      keyword: 'ladies bridal jewellery dubai',
      match_type: 'phrase',
      category: 'Bridal',
      intent: 'transactional',
      source: 'search_console',
      status: 'active',
      priority: 94,
      monthly_volume: 8100,
      competition: 0.72,
      cpc: 5.6,
      trend: 'rising',
      performance_score: 0.87,
      impressions: 32100,
      clicks: 2840,
      conversions: 38,
    },
    {
      id: 'kw_whatsapp',
      org_id: '00000000-0000-0000-0000-000000000001',
      keyword: 'women eid gift jewellery',
      match_type: 'broad',
      category: 'Gifts',
      intent: 'commercial',
      source: 'whatsapp',
      status: 'active',
      priority: 88,
      monthly_volume: 6200,
      competition: 0.58,
      cpc: 4.2,
      trend: 'rising',
      performance_score: 0.8,
      impressions: 22100,
      clicks: 1640,
      conversions: 24,
    },
    {
      id: 'kw_private',
      org_id: '00000000-0000-0000-0000-000000000001',
      keyword: 'luxury ladies perfume uae',
      match_type: 'exact',
      category: 'Perfume',
      intent: 'commercial',
      source: 'ai_suggested',
      status: 'active',
      priority: 79,
      monthly_volume: 4300,
      competition: 0.49,
      cpc: 3.1,
      trend: 'stable',
      performance_score: 0.73,
      impressions: 17600,
      clicks: 920,
      conversions: 11,
    },
  ],
  seo_reports: [
    {
      id: 'seo_2026_05_25',
      org_id: '00000000-0000-0000-0000-000000000001',
      report_date: '2026-05-25',
      overall_score: 84,
      performance_score: 82,
      accessibility_score: 91,
      best_practices_score: 86,
      seo_score: 78,
      total_pages: 126,
      indexed_pages: 108,
      crawl_errors: 2,
      broken_links: 3,
      missing_meta: 12,
      slow_pages: 5,
      mobile_issues: 4,
      top_issues: [{ label: 'Missing ladies bridal meta copy', severity: 'medium' }],
      recommendations: [
        { action: 'Rewrite bridal collection meta around ladies-only intent', impact: '+9% qualified clicks', priority: 'high' },
        { action: 'Add Arabic FAQ blocks for delivery and payment reassurance', impact: '+14% WhatsApp handoff rate', priority: 'medium' },
        { action: 'Compress private drop images on mobile', impact: '+6 performance score', priority: 'medium' },
      ],
    },
  ],
  keyword_extractions: [
    {
      id: 'ke_1',
      org_id: '00000000-0000-0000-0000-000000000001',
      source_type: 'message',
      extracted_text: 'bridal jewellery for ladies delivery before Thursday',
      normalized_keyword: 'ladies bridal jewellery delivery uae',
      confidence: 0.86,
      intent: 'transactional',
      suggested_match_type: 'phrase',
      suggested_products: ['LE Celestial Bridal Set'],
      is_processed: false,
      created_at: '2026-05-25T12:30:00Z',
    },
    {
      id: 'ke_2',
      org_id: '00000000-0000-0000-0000-000000000001',
      source_type: 'session',
      extracted_text: 'women eid gifts ruby bangle',
      normalized_keyword: 'women eid gift ruby bangle',
      confidence: 0.79,
      intent: 'commercial',
      suggested_match_type: 'broad',
      suggested_products: ['Ruby Bangle for Ladies'],
      is_processed: false,
      created_at: '2026-05-25T11:22:00Z',
    },
  ],
  search_console_data: [
    { id: 'sc_1', query: 'ladies bridal jewellery dubai', page: '/collections/bridal', device: 'mobile', impressions: 8400, clicks: 730, ctr: 0.086, position: 3.8 },
    { id: 'sc_2', query: 'women eid gift jewellery', page: '/collections/eid-gifts', device: 'mobile', impressions: 6100, clicks: 410, ctr: 0.067, position: 5.2 },
    { id: 'sc_3', query: 'luxury ladies perfume uae', page: '/products/oud-royal', device: 'desktop', impressions: 2800, clicks: 145, ctr: 0.052, position: 6.9 },
  ],
  whatsapp_templates: [
    {
      id: 'tpl_payment_confirm',
      name: 'Payment confirmation',
      category: 'utility',
      language: 'Arabic + English',
      status: 'approved',
      quality: 96,
      body: 'Thank you, {first_name}. We received your payment screenshot and finance is verifying it now.',
      use_case: 'Bank transfer and payment proof follow-up',
      owner: 'Arslan',
    },
    {
      id: 'tpl_bridal_deadline',
      name: 'Bridal delivery promise',
      category: 'utility',
      language: 'Arabic',
      status: 'approved',
      quality: 92,
      body: 'Your bridal order is reserved. We are confirming delivery timing before Thursday evening.',
      use_case: 'Urgent female bridal customers',
      owner: 'Abdelrahman',
    },
    {
      id: 'tpl_eid_vip',
      name: 'VIP Eid private drop',
      category: 'marketing',
      language: 'Arabic + English',
      status: 'pending',
      quality: 84,
      body: 'A private ladies Eid drop is available for VIP clients before public launch.',
      use_case: 'VIP repeat women buyers',
      owner: 'Ahmed',
    },
    {
      id: 'tpl_cart_recovery',
      name: 'Cart recovery concierge',
      category: 'marketing',
      language: 'English',
      status: 'approved',
      quality: 89,
      body: 'I can reserve these pieces and confirm delivery timing before you complete checkout.',
      use_case: 'Abandoned ladies jewellery carts',
      owner: 'Mohamed',
    },
  ],
};

export const DAILY_REPORTS = [
  { title: 'Executive daily room summary', owner: 'Omnia AI', status: 'ready', time: '09:00', audience: 'Owner and admin' },
  { title: 'WhatsApp ladies concierge quality', owner: 'Abdelrahman', status: 'needs review', time: '12:00', audience: 'Customer desk' },
  { title: 'Finance verification risk', owner: 'Mahmoud', status: 'ready', time: '15:00', audience: 'Finance' },
  { title: 'Google and keyword mining', owner: 'Ahmed', status: 'scheduled', time: '18:00', audience: 'Marketing' },
];

export const BRAND_SIGNALS = [
  { label: 'Luxury trust', score: 91, detail: 'VIP female customers respond to private drop language.' },
  { label: 'Bridal urgency', score: 86, detail: 'Deadline and delivery certainty outperform discount offers.' },
  { label: 'Arabic reassurance', score: 79, detail: 'Arabic WhatsApp replies improve payment completion.' },
  { label: 'Discount risk', score: 42, detail: 'Price language lowers premium perception for bridal sets.' },
];

export const WHATSAPP_COMMAND_CENTER = {
  number: '+971 56 547 8227',
  health: 94,
  sla: '4m 12s',
  openThreads: 18,
  owner: 'Abdelrahman',
  policy: 'Ladies-only concierge. Every reply must protect privacy, delivery certainty, and brand value.',
};

export const WHATSAPP_OPTIONS = [
  { id: 'inbox', label: 'Inbox', metric: '18 open', detail: 'All WhatsApp conversations and unread handoffs' },
  { id: 'sales', label: 'Sales', metric: 'AED 64.8k', detail: 'Order intent, carts, bundles, and payment readiness' },
  { id: 'catalog', label: 'Catalog', metric: '4 SKUs', detail: 'Send products, reserve stock, and attach ladies-only product cards' },
  { id: 'labels', label: 'Labels', metric: '9 labels', detail: 'VIP, bridal, payment, KSA, recovery, and quality labels' },
  { id: 'templates', label: 'Templates', metric: '4 live', detail: 'Approved WhatsApp utility and marketing templates' },
  { id: 'broadcasts', label: 'Broadcasts', metric: '3 segments', detail: 'VIP, bridal, Eid, and recovery campaign sends' },
  { id: 'automation', label: 'Automation', metric: '7 rules', detail: 'Routing, SLA, language, cart, and finance triggers' },
  { id: 'quality', label: 'Quality', metric: '91 score', detail: 'Arabic tone, brand compliance, and privacy checks' },
  { id: 'team', label: 'Team', metric: '4 agents', detail: 'Male operator workload, skills, and reassignment' },
  { id: 'finance', label: 'Finance', metric: '2 pending', detail: 'Payment proof, COD risk, BNPL, and fraud review' },
];

export const WHATSAPP_BROADCASTS = [
  {
    id: 'bc_vip_eid',
    name: 'VIP ladies Eid private drop',
    audience: '84 VIP women',
    status: 'ready',
    owner: 'Ahmed',
    expectedRevenue: 'AED 48k',
    guardrail: 'Send only to opted-in VIP buyers with prior purchase history.',
  },
  {
    id: 'bc_bridal_delivery',
    name: 'Bridal delivery certainty',
    audience: '146 bridal collectors',
    status: 'review',
    owner: 'Abdelrahman',
    expectedRevenue: 'AED 62k',
    guardrail: 'No discount language. Lead with reservation and delivery promise.',
  },
  {
    id: 'bc_cart_recovery',
    name: 'Ladies cart recovery',
    audience: '39 abandoned carts',
    status: 'scheduled',
    owner: 'Mohamed',
    expectedRevenue: 'AED 18k',
    guardrail: 'Recover with concierge help, not mass-promo language.',
  },
];

export const WHATSAPP_AUTOMATIONS = [
  { name: 'VIP women priority route', trigger: 'LTV above AED 8,000', action: 'Assign to Abdelrahman', enabled: true },
  { name: 'Payment screenshot triage', trigger: 'Image after order intent', action: 'Create finance verification', enabled: true },
  { name: 'Bridal deadline escalation', trigger: 'Thursday, wedding, urgent, Riyadh', action: 'Notify owner and senior agent', enabled: true },
  { name: 'Arabic reassurance', trigger: 'Arabic buyer + payment/delivery worry', action: 'Suggest approved Arabic reply', enabled: true },
  { name: 'Cart recovery', trigger: 'Abandoned cart over AED 700', action: 'Offer reserve and delivery check', enabled: true },
  { name: 'Discount guard', trigger: 'Agent drafts discount first', action: 'Warn and suggest concierge wording', enabled: true },
  { name: 'Quiet hours', trigger: 'After 22:30 UAE', action: 'Use polite delayed response template', enabled: false },
];

export const WHATSAPP_QUALITY_CHECKS = [
  { label: 'Ladies-only relevance', score: 98, issue: 'All active templates target women buyers.' },
  { label: 'Arabic tone', score: 88, issue: 'Two replies need warmer delivery reassurance.' },
  { label: 'Luxury positioning', score: 82, issue: 'Avoid leading with discounts in cart recovery.' },
  { label: 'Privacy', score: 96, issue: 'No sensitive payment details exposed in draft messages.' },
  { label: 'SLA', score: 79, issue: 'Mariam K. bridal thread breached 10 minute priority SLA.' },
];

export const WHATSAPP_TEAM_LOAD = [
  { name: 'Abdelrahman', role: 'WhatsApp manager', open: 6, vip: 3, score: 92, next: 'Take Mariam K. from Abdallah' },
  { name: 'Arslan', role: 'Payment verification', open: 5, vip: 1, score: 86, next: 'Clear Noura bank transfer' },
  { name: 'Abdallah', role: 'KSA market', open: 2, vip: 1, score: 81, next: 'Offline, reassign urgent bridal' },
  { name: 'Mohamed', role: 'Junior concierge', open: 5, vip: 0, score: 74, next: 'Use approved recovery templates only' },
];

export const WHATSAPP_LABELS = [
  { name: 'VIP lady', count: 84, action: 'Senior manager only' },
  { name: 'Bridal deadline', count: 17, action: 'Escalate delivery promise' },
  { name: 'Payment proof', count: 9, action: 'Finance verification' },
  { name: 'KSA delivery', count: 11, action: 'Route to KSA operator' },
  { name: 'Cart recovery', count: 39, action: 'Send concierge recovery' },
  { name: 'Arabic only', count: 52, action: 'Arabic template first' },
  { name: 'BNPL request', count: 8, action: 'Manager approval' },
  { name: 'Refund risk', count: 4, action: 'Finance + owner review' },
  { name: 'Private drop', count: 22, action: 'Reserve limited stock' },
];

export const WHATSAPP_CATALOG_ACTIONS = [
  { sku: 'OMN-RB-001', name: 'Ruby Bangle for Ladies', stock: 18, action: 'Send product card + price parity note' },
  { sku: 'OMN-MP-002', name: 'Moonstone Pendant for Ladies', stock: 3, action: 'Reserve before sending because stock is low' },
  { sku: 'OMN-LC-003', name: 'LE Celestial Bridal Set', stock: 8, action: 'Confirm delivery deadline before payment' },
  { sku: 'OMN-PF-001', name: 'Oud Royal Perfume for Ladies', stock: 42, action: 'Bundle with bridal and Eid gift chats' },
];

export function getMockTableData(table: string) {
  return MOCK_TABLES[table] ? [...MOCK_TABLES[table]] : [];
}
